# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InLocalCustomer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InLocalCustomer


pod 'IQKeyboardManagerSwift', '~> 6.4.1'  
pod 'AlamofireObjectMapper'
pod 'LanguageManager-iOS'
pod 'Toast-Swift', '~> 4.0.0'
pod 'UITextView+Placeholder'
pod 'JGProgressHUD'
pod 'GoogleMaps'
pod 'GooglePlaces'

pod 'AZTabBar'
pod 'OTPFieldView'
pod 'CalendarDateRangePicker'
pod 'CountryList'
pod 'DatePickerDialog'
pod 'DateTimePicker'

end
