# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'InLocalCustomer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InLocalCustomer


pod 'IQKeyboardManagerSwift', '~> 6.4.1'  
pod 'AlamofireObjectMapper'
pod 'LanguageManager-iOS'
pod 'Toast-Swift', '~> 4.0.0'
pod 'UITextView+Placeholder'
pod 'JGProgressHUD'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SDWebImage'
pod 'Firebase/Messaging'

pod 'AZTabBar'
pod 'OTPFieldView'
pod 'CalendarDateRangePicker'
pod 'CountryList'
pod 'DatePickerDialog'
pod 'DateTimePicker'
pod 'ImageCropper'
pod 'CountryPickerView'

end
deployment_target = '12.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
